import DynamicPage, { type Block } from "@/components/DynamicPage";

const fallbackBlocks: Block[] = [
  { id: "1", type: "hero", content: { heading: "Disclaimer", subheading: "Limitations of Liability & General Notices · Effective Date: June 1, 2025" } },

  { id: "2", type: "text", content: { heading: "", body: "*This Disclaimer governs your use of dynime.com and all associated services. Please read it carefully. By using the Services, you acknowledge and agree to the terms set out below.*" } },

  { id: "3", type: "text", content: { heading: "1. General Disclaimer", body: "The information and services provided by Dynime LLC on dynime.com are for general business management purposes only. While we strive for accuracy and reliability, we make no representations, warranties, or guarantees, express or implied, about the completeness, accuracy, reliability, suitability, or availability of the platform." } },

  { id: "4", type: "text", content: { heading: "2. No Professional Advice", body: "The content, tools, templates, reports, and outputs generated by Dynime (including accounting reports, HR documents, financial summaries, and legal document templates) are provided for general informational and operational purposes only. They do **NOT** constitute:\n\n• Legal advice or legal services\n• Financial, investment, or accounting advice\n• Tax planning or tax compliance guidance\n• Human resources or employment law advice\n• Medical, psychological, or health-related recommendations\n\nAlways consult qualified professionals — including attorneys, certified accountants (CPA/CA), tax advisors, and HR specialists — before making decisions based on data or outputs generated by Dynime." } },

  { id: "5", type: "text", content: { heading: "3. Accounting & Financial Tools Disclaimer", body: "Dynime's accounting, invoicing, and financial reporting features are software tools designed to assist in bookkeeping and financial record-keeping. We do not guarantee that outputs will satisfy the requirements of any specific accounting standard (GAAP, IFRS, etc.), tax authority, or regulatory body. Users are solely responsible for verifying financial data and ensuring compliance with applicable financial regulations." } },

  { id: "6", type: "text", content: { heading: "4. HR & Payroll Disclaimer", body: "Dynime's HRM and payroll modules provide tools to assist in managing employee information and payroll calculations. Employment laws, tax rates, and labor regulations vary by jurisdiction and change frequently. Dynime does not guarantee that payroll calculations or HR documents meet the legal requirements of your specific jurisdiction. Always verify with qualified employment lawyers or payroll specialists." } },

  { id: "7", type: "text", content: { heading: "5. Third-Party Integrations", body: "Dynime integrates with third-party services (payment gateways, email providers, cloud storage, etc.). We are not responsible for the accuracy, reliability, availability, security, or content of third-party services. Third-party use is governed by their respective terms of service and privacy policies." } },

  { id: "8", type: "text", content: { heading: "6. No Warranty", body: "TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, DYNIME EXPRESSLY DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT. We do not warrant that the Services will be uninterrupted, error-free, completely secure, or free from viruses or other harmful components." } },

  { id: "9", type: "text", content: { heading: "7. Limitation of Damages", body: "IN NO EVENT SHALL DYNIME, ITS AFFILIATES, OFFICERS, DIRECTORS, EMPLOYEES, AGENTS, OR LICENSORS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATING TO YOUR USE OF THE SERVICES, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES." } },

  { id: "10", type: "text", content: { heading: "8. Accuracy of Information", body: "While we make reasonable efforts to keep our platform content current and accurate, information may become outdated, contain inaccuracies, or be incomplete. We reserve the right to change, update, or remove content at any time without notice. We accept no liability for decisions made based on information from the platform." } },

  { id: "11", type: "text", content: { heading: "9. External Links", body: "Dynime may contain links to external websites. These are provided for convenience only. We have no control over the content of those sites and accept no responsibility for them or for any loss or damage that may arise from your use of them." } },

  { id: "12", type: "text", content: { heading: "10. Compliance Responsibility", body: "You are solely responsible for ensuring that your use of Dynime complies with all laws, regulations, and industry standards applicable to your business, including but not limited to GDPR, HIPAA, SOX, PCI-DSS, local labor laws, and financial regulations. Dynime is a tool to assist your operations — we are not a compliance officer or legal guarantor." } },

  { id: "13", type: "text", content: { heading: "11. Forward-Looking Statements", body: "Any statements about future features, platform improvements, or roadmap items made by Dynime on the website, in marketing materials, or in communications are aspirational and subject to change. We make no binding commitments regarding future functionality." } },

  { id: "14", type: "text", content: { heading: "12. Applicable Law", body: "If any part of this disclaimer is found to be unenforceable under applicable law, that part will be construed as far as possible to reflect the parties' original intentions. The remaining provisions of this disclaimer shall continue in full force and effect." } },

  { id: "15", type: "text", content: { heading: "13. Contact", body: "For questions regarding this Disclaimer, contact:\n\n| | |\n|---|---|\n| **General Contact** | contact@dynime.com |\n| **Support** | support@dynime.com |\n| **Company** | Dynime LLC |\n| **Address** | 2B, 16, 16/1 Basubazar Lane, Dayaganj, Wari, Dhaka, 1100, Bangladesh |\n\n*Last Updated: June 1, 2025 · Version 1.0 · dynime.com/disclaimer*" } },
];

export default function Disclaimer() {
  return <DynamicPage slug="/disclaimer" fallbackTitle="Disclaimer" fallbackBlocks={fallbackBlocks} />;
}
