import DynamicPage, { type Block } from "@/components/DynamicPage";

const fallbackBlocks: Block[] = [
  { id: "1", type: "hero", content: { heading: "Privacy Policy", subheading: "Dynime Business Management Platform · Effective Date: June 1, 2025" } },

  { id: "2", type: "text", content: { heading: "", body: "*This Privacy Policy explains how Dynime LLC collects, uses, stores, shares, and protects your personal data when you use our platform at dynime.com. We are committed to transparency and compliance with global privacy regulations including GDPR, CCPA, and PIPEDA.*" } },

  { id: "3", type: "text", content: { heading: "1. Who We Are", body: "Dynime LLC (\"Dynime,\" \"we,\" \"us,\" or \"our\") operates the business management software platform available at dynime.com. We are the data controller responsible for personal data collected through our Services.\n\n| | |\n|---|---|\n| **Company** | Dynime LLC |\n| **Website** | dynime.com |\n| **General Contact** | contact@dynime.com |\n| **Support** | support@dynime.com |\n| **Sales** | sales@dynime.com |\n| **Address** | 2B, 16, 16/1 Basubazar Lane, Dayaganj, Wari, Dhaka, 1100, Bangladesh |" } },

  { id: "4", type: "text", content: { heading: "2. Information We Collect", body: "**2.1 Account & Identity Information**\n• Full name, email address, phone number, job title, and company name\n• Username, password (hashed), and profile photograph\n• Billing address, VAT/tax ID numbers for invoicing purposes\n• Government-issued ID only where required for identity verification\n\n**2.2 Business & Operational Data**\n• CRM data: customer names, contacts, deals, pipeline information\n• HRM data: employee records, payroll information, leave requests, performance data\n• Accounting data: financial transactions, invoices, payments, reports\n• Project data: tasks, milestones, timelines, files, and comments\n\n**2.3 Payment & Billing Information**\nWe use PCI-DSS-compliant payment processors (Stripe, PayPal, Paddle) to handle all payment card data. Dynime does not store, process, or transmit raw card numbers. We retain:\n• Transaction IDs, payment status, and invoice references\n• Billing address and last four digits of payment cards (tokenized)\n• Subscription plan details and billing history\n\n**2.4 Usage & Technical Data**\n• IP address, browser type, operating system, and device identifiers\n• Pages visited, features used, session duration, and click events\n• API usage logs, error reports, and system diagnostics\n• Cookies and similar tracking technologies (see Cookie section)\n\n**2.5 Communications**\n• Support tickets, chat messages, and email correspondence\n• Survey responses and feedback submissions\n• Marketing preferences and communication opt-ins" } },

  { id: "5", type: "text", content: { heading: "3. Legal Basis for Processing (GDPR)", body: "For users in the European Economic Area (EEA), we process your data under the following legal bases:\n\n• **Contract Performance**: To provide the Services you subscribed to\n• **Legitimate Interests**: Security, fraud prevention, improving our platform\n• **Legal Obligation**: Tax records, financial compliance, regulatory requirements\n• **Consent**: Marketing emails, optional analytics, cookie tracking\n• **Vital Interests**: Emergency situations where data sharing is necessary to protect life" } },

  { id: "6", type: "text", content: { heading: "4. How We Use Your Information", body: "• Providing, operating, and improving the Dynime platform and Services\n• Processing payments, managing subscriptions, and issuing invoices\n• User authentication, security monitoring, and fraud prevention\n• Customer support, troubleshooting, and technical assistance\n• Sending transactional notifications (invoices, account alerts, security notices)\n• Sending marketing communications (only with your consent; opt-out available at all times)\n• Compliance with applicable laws, regulations, and legal proceedings" } },

  { id: "7", type: "text", content: { heading: "5. Cookies & Tracking Technologies", body: "We use cookies and similar technologies. You may manage preferences via our Cookie Consent Manager:\n\n• **Strictly Necessary Cookies**: Required for login sessions and security. Cannot be disabled.\n• **Functional Cookies**: Remember your preferences and settings.\n• **Analytics Cookies**: Measure platform performance (Google Analytics, Mixpanel).\n• **Marketing Cookies**: Used for targeted advertising (only with consent).\n\nYou may withdraw consent for non-essential cookies at any time via Settings > Privacy.\n\nFor full details, see our [Cookie Policy](/cookies)." } },

  { id: "8", type: "text", content: { heading: "6. Data Sharing & Third Parties", body: "**6.1 Payment Processors**\n• Stripe, Inc. (stripe.com) — Subject to Stripe's Privacy Policy\n• PayPal Holdings, Inc. (paypal.com) — Subject to PayPal's Privacy Policy\n• Paddle.com Market Ltd. (paddle.com) — Subject to Paddle's Privacy Policy\n\n**6.2 Infrastructure & Cloud Providers**\n• Amazon Web Services (AWS) — Hosting and data storage\n• Google Cloud Platform — Backup and analytics\n• Cloudflare — CDN and DDoS protection\n\n**6.3 Other Service Providers**\n• Email: SendGrid / Amazon SES for transactional emails\n• Support: Intercom or Zendesk for customer support tickets\n• Analytics: Google Analytics 4, Mixpanel (anonymized data only)\n• Security: Datadog for system monitoring and anomaly detection\n\nWe do **NOT** sell, rent, or trade your personal data to any third party for their marketing purposes." } },

  { id: "9", type: "text", content: { heading: "7. International Data Transfers", body: "Dynime operates globally. When transferring data outside the EEA, we use:\n\n• Standard Contractual Clauses (SCCs) approved by the European Commission" } },

  { id: "10", type: "text", content: { heading: "8. Data Retention", body: "• **Active account data**: Retained for the duration of your subscription\n• **Account data after cancellation**: 90 days, then anonymized or deleted\n• **Financial records** (invoices, payments): 7 years for legal/tax compliance\n• **Support communications**: 3 years\n• **Anonymized analytics data**: Up to 5 years\n• **Backup copies**: Purged within 30 days of deletion request" } },

  { id: "11", type: "text", content: { heading: "9. Your Rights", body: "**Under GDPR (EEA Users)**\n• Right to Access — Request a copy of your personal data\n• Right to Rectification — Correct inaccurate data\n• Right to Erasure (\"Right to be Forgotten\") — Request deletion of your data\n• Right to Restrict Processing — Limit how we use your data\n• Right to Data Portability — Receive data in a machine-readable format\n• Right to Object — Object to processing based on legitimate interests\n• Rights Related to Automated Decision-Making — Challenge automated decisions\n\n**Under CCPA (California Residents)**\n• Right to Know — What personal information is collected and how it is used\n• Right to Delete — Request deletion of personal information\n• Right to Opt-Out — Opt out of sale of personal information (we do not sell data)\n• Right to Non-Discrimination — We will not discriminate for exercising your rights\n\nTo exercise any of these rights, email privacy@dynime.com with your full name, email address, and request. We will respond within 30 days (GDPR) or 45 days (CCPA)." } },

  { id: "12", type: "text", content: { heading: "10. Data Security", body: "• AES-256 encryption at rest; TLS 1.3 encryption in transit\n• SOC 2 Type II compliance audited annually\n• Multi-factor authentication (MFA) enforced for all staff accounts\n• Role-based access controls (RBAC) limiting data access by job function\n• Regular penetration testing and vulnerability assessments\n• Security incident response plan with 72-hour breach notification (GDPR)\n• GDPR Article 32 compliant technical and organizational measures" } },

  { id: "13", type: "text", content: { heading: "11. Children's Privacy", body: "The Dynime platform is not intended for individuals under the age of 16 (or 13 in the US). We do not knowingly collect personal data from minors. If you believe a minor has provided us data, contact privacy@dynime.com immediately." } },

  { id: "14", type: "text", content: { heading: "12. Changes to This Policy", body: "We may update this Privacy Policy periodically. Material changes will be communicated via email or in-platform notification at least 30 days before taking effect. Continued use after the effective date constitutes acceptance of the revised policy." } },

  { id: "15", type: "text", content: { heading: "13. Contact & Complaints", body: "For privacy-related inquiries or complaints, please contact us:\n\n| | |\n|---|---|\n| **General Contact** | contact@dynime.com |\n| **Support** | support@dynime.com |\n| **Postal Address** | 2B, 16, 16/1 Basubazar Lane, Dayaganj, Wari, Dhaka, 1100, Bangladesh |\n\nEU residents may also lodge a complaint with their local data protection authority (supervisory authority). UK residents may contact the Information Commissioner's Office (ICO).\n\n*Last Updated: June 1, 2025 · Version 1.0 · dynime.com/privacy*" } },
];

export default function Privacy() {
  return <DynamicPage slug="/privacy" fallbackTitle="Privacy Policy" fallbackBlocks={fallbackBlocks} />;
}
