import DynamicPage, { type Block } from "@/components/DynamicPage";

const fallbackBlocks: Block[] = [
  { id: "1", type: "hero", content: { heading: "Terms & Conditions", subheading: "Dynime Business Management Platform · Effective Date: June 1, 2025" } },

  { id: "2", type: "text", content: { heading: "Agreement to Terms", body: "These Terms & Conditions (\"Terms,\" \"Agreement\") constitute a legally binding agreement between you (\"User,\" \"Customer,\" \"you,\" or \"your\") — whether as an individual or on behalf of an organization — and Dynime LLC (\"Dynime,\" \"Company,\" \"we,\" \"us,\" or \"our\"), governing your access to and use of the Dynime platform, including all websites, web applications, mobile applications, APIs, integrations, professional services, documentation, and any related services (collectively, the \"Service\").\n\nBy creating an account, accessing, or using any part of the Service, you represent that: (a) you have read, understood, and agree to be bound by these Terms; (b) you are of legal age in your jurisdiction to form a binding contract; and (c) if you are accepting on behalf of an organization, you have the authority to bind that organization to these Terms.\n\nIF YOU DO NOT AGREE TO ALL OF THESE TERMS, YOU ARE PROHIBITED FROM USING THE SERVICE AND MUST DISCONTINUE USE IMMEDIATELY.\n\nThese Terms incorporate by reference our [Privacy Policy](/privacy), [Acceptable Use Policy](/acceptable-use), [Cookie Policy](/cookies), and [Data Processing Agreement](/dpa)." } },

  { id: "3", type: "text", content: { heading: "1. Definitions", body: "• **\"Account\"** means the unique account created for you to access our Service, including any sub-accounts or user seats within a Tenant organization.\n• **\"Authorized User\"** means any individual who is permitted to use the Service under your Account.\n• **\"Confidential Information\"** means any non-public information disclosed by either party that is designated as confidential.\n• **\"Customer Data\"** means all data, content, files, documents, and materials that you or your Authorized Users upload, create, import, transmit, or store through the Service.\n• **\"Documentation\"** means the user guides, help articles, API documentation, and other technical materials we provide.\n• **\"Service\"** means the Dynime cloud-based business management platform and all related applications, features, and functionality.\n• **\"Subscription Period\"** means the term for which you have subscribed to the Service.\n• **\"Tenant\"** means a company, organization, or entity that has registered an Account on the Dynime platform.\n• **\"Third-Party Services\"** means services, applications, integrations, and APIs provided by parties other than Dynime." } },

  { id: "4", type: "text", content: { heading: "2. Eligibility & Account Registration", body: "**2.1 Eligibility Requirements**\nTo use the Service, you must:\n• Be at least 16 years of age (or the minimum age of digital consent in your jurisdiction)\n• Have the legal capacity to enter into a binding contract\n• Not be barred from receiving services under the laws of your jurisdiction\n• If registering on behalf of an organization, have full authority to bind that organization\n\n**2.2 Account Creation**\n• You must provide accurate, current, and complete registration information\n• Each individual user must have their own unique account\n• You are responsible for maintaining the confidentiality and security of your login credentials\n\n**2.3 Account Security**\n• You are solely responsible for all activities that occur under your Account\n• You must enable multi-factor authentication (MFA) for all administrative accounts where available\n• You must immediately notify us at security@dynime.com upon becoming aware of any unauthorized access\n\n**2.4 Multi-Tenant Accounts**\n• Each Tenant organization has one or more Company Administrators with elevated permissions\n• Company Administrators are responsible for managing user access, roles, and permissions\n• The organization that registered the Tenant Account is the contracting party for billing purposes" } },

  { id: "5", type: "text", content: { heading: "3. The Service", body: "**3.1 Service Description**\nDynime is a cloud-based, multi-tenant business management platform offering integrated modules including:\n• **HRMS**: Employee management, attendance, leave, payroll, recruitment, and performance reviews\n• **CRM**: Deal pipeline, contact management, lead tracking, and customer relationship tools\n• **Accounting**: Invoicing, expense management, payments, tax calculations, and financial reporting\n• **Marketing**: Campaign management, email templates, analytics, and automation\n• **Helpdesk**: Ticket management, customer support workflows, and knowledge base\n• **Project Management**: Task boards, project tracking, collaboration, and resource allocation\n• **Document Management**: File storage, version control, sharing, and collaboration\n• **Point of Sale (POS)**: Product catalog, orders, inventory, and courier integration\n• **Workflows**: Custom business process automation, approval chains, and task routing\n• **Reports & Analytics**: Dashboards, custom reports, data visualization, and business intelligence\n\n**3.2 Service Availability**\n• We target 99.9% uptime for the Service (measured monthly, excluding scheduled maintenance)\n• Scheduled maintenance windows are communicated at least 48 hours in advance\n\n**3.3 Service Modifications**\n• We continuously improve the Service and may add, modify, or remove features with reasonable notice\n• For material changes that negatively impact your use, we will provide at least 30 days' prior written notice\n\n**3.4 API & Integration Access**\n• API access is subject to rate limits, authentication requirements, and our API Terms of Use\n• We may update API versions and deprecate older versions with at least 6 months' notice" } },

  { id: "6", type: "text", content: { heading: "4. Subscription Plans, Billing & Payment", body: "**4.1 Plans & Pricing**\n• The Service is available under multiple subscription tiers (Free, Starter, Professional, Enterprise) with varying feature sets and usage limits\n• Pricing may be updated with at least 30 days' prior notice\n\n**4.2 Free Trial**\n• All paid plans include a complimentary free trial period (default 14 days)\n• No payment information or credit card is required to begin a free trial\n• At the end of the trial, you must actively subscribe. We will not auto-charge you\n\n**4.3 Billing & Payment Terms**\n• Paid subscriptions are billed in advance on a recurring basis (monthly, quarterly, or annually)\n• All fees are quoted exclusive of applicable taxes, duties, levies, or withholdings\n• You will be charged by **Dynime LLC**\n• Accepted payment methods include credit/debit cards, bank transfers, and regional payment providers (Stripe, SSLCommerz, bKash, Nagad, PayPal, Paddle, Dodo Payments)\n\n**4.4 Automatic Renewal**\n• Subscriptions automatically renew unless cancelled before the renewal date\n• A renewal reminder is sent via email at least 7 days before renewal" } },

  { id: "7", type: "text", content: { heading: "5. Cancellation, Suspension & Refunds", body: "**5.1 Cancellation by You**\n• You may cancel your subscription at any time through Settings → Subscription or by contacting support@dynime.com\n• Cancellation takes effect at the end of your current Subscription Period\n• No prorated refunds are issued for unused time\n\n**5.2 Data Export & Retention After Cancellation**\n• You may export your Customer Data within 30 days after your subscription ends\n• After the 30-day export window, all Customer Data will be permanently deleted\n\n**5.3 Suspension by Us**\n• We may suspend your access immediately if you breach these Terms, your payment is past due, or we detect fraudulent activity\n\n**5.4 Refund Policy**\n• Refund eligibility is governed by our separate [Refund Policy](/refund)" } },

  { id: "8", type: "text", content: { heading: "6. Customer Data & Intellectual Property", body: "**6.1 Your Customer Data**\n• You retain full ownership of all Customer Data\n• You grant Dynime a limited license to use your Customer Data solely to provide the Service\n\n**6.2 Dynime Intellectual Property**\n• The Service is the exclusive property of Dynime LLC and its licensors\n• These Terms grant you a limited, non-exclusive, non-transferable, revocable license to access and use the Service" } },

  { id: "9", type: "text", content: { heading: "7. Acceptable Use Policy", body: "You agree to use the Service responsibly and in compliance with all applicable laws. Full details are available in our [Acceptable Use Policy](/acceptable-use).\n\nViolation of the Acceptable Use Policy may result in:\n• Warning and request to remedy the violation\n• Temporary suspension of the offending Account\n• Permanent termination of your Account without refund\n• Reporting to law enforcement authorities where legally required" } },

  { id: "10", type: "text", content: { heading: "8. Data Protection & Privacy", body: "• Our collection, use, storage, and protection of Personal Data is governed by our [Privacy Policy](/privacy)\n• Customer Data is logically isolated between Tenants using Row-Level Security (RLS)\n• You may export your Customer Data at any time in standard formats (CSV, JSON, PDF)" } },

  { id: "11", type: "text", content: { heading: "9. Warranties & Disclaimers", body: "**9.1 Dynime Warranties**\nWe warrant that the Service will perform materially in accordance with the applicable Documentation during your Subscription Period.\n\n**9.2 Disclaimers**\nEXCEPT AS EXPRESSLY SET FORTH IN THIS SECTION, THE SERVICE IS PROVIDED ON AN \"AS IS\" AND \"AS AVAILABLE\" BASIS. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, DYNIME DISCLAIMS ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE." } },

  { id: "12", type: "text", content: { heading: "10. Limitation of Liability", body: "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL DYNIME TECHNOLOGIES LTD., ITS DIRECTORS, OFFICERS, EMPLOYEES, AGENTS, SUPPLIERS, LICENSORS, OR AFFILIATES BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, OR EXEMPLARY DAMAGES.\n\nDYNIME'S TOTAL AGGREGATE LIABILITY SHALL NOT EXCEED THE GREATER OF: (a) THE TOTAL AMOUNTS PAID BY YOU IN THE TWELVE (12) MONTHS PRECEDING THE EVENT; OR (b) ONE HUNDRED US DOLLARS ($100)." } },

  { id: "13", type: "text", content: { heading: "11. Governing Law & Jurisdiction", body: "This Agreement shall be governed by and construed in accordance with the laws of Bangladesh. For any disputes not subject to arbitration, you agree to submit to the exclusive personal jurisdiction of the courts of Bangladesh." } },

  { id: "14", type: "text", content: { heading: "12. Changes to These Terms", body: "We reserve the right to modify these Terms at any time.\n\n• **Material Changes**: We will provide at least 30 days' advance notice via email\n• **Continued Use**: Your continued use after the effective date constitutes acceptance\n• **Disagreement**: If you disagree with any changes, you must stop using the Service before the changes take effect" } },

  { id: "15", type: "text", content: { heading: "13. Contact Information", body: "If you have any questions regarding these Terms, please contact us:\n\n| | |\n|---|---|\n| **General Contact** | contact@dynime.com |\n| **Support** | support@dynime.com |\n| **Sales** | sales@dynime.com |\n| **Address** | 2B, 16, 16/1 Basubazar Lane, Dayaganj, Wari, Dhaka, 1100, Bangladesh |\n\n*Last Updated: June 1, 2025 · Version 1.0 · dynime.com/terms*" } },
];

export default function Terms() {
  return <DynamicPage slug="/terms" fallbackTitle="Terms & Conditions" fallbackBlocks={fallbackBlocks} />;
}
